# spring security OAuth 2.0 authorization server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.example.com     # Replace with your OAuth provider

# Enable Gzip Compression
server:
  compression:
    enabled: true

# Connection Pooling with HikariCP
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
